# Generated by Django 3.1 on 2021-09-22 07:54

from django.db import migrations, models
import django.db.models.deletion
import sunnysouth.lib.models
import sunnysouth.marketplace.models.assets


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('marketplace', '0002_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AlterField(
            model_name='address',
            name='addressable_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=sunnysouth.lib.models.generate_uuid, max_length=300, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('image', models.FileField(null=True, upload_to=sunnysouth.marketplace.models.assets.resolve_asset_directory_path)),
                ('attachable_object_id', models.IntegerField()),
                ('attachable_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
