# Generated by Django 3.1 on 2021-10-31 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('marketplace', '0006_auto_20211031_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='attachable_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
