# Generated by Django 3.0.6 on 2020-05-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_client',
            field=models.BooleanField(default=True, help_text='Consumer of products or services.', null=True, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_supplier',
            field=models.BooleanField(default=False, help_text='Product or Service Provider', null=True, verbose_name='supplier'),
        ),
    ]
