# Generated by Django 3.0.6 on 2020-05-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200530_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_supplier',
            field=models.BooleanField(default=False, help_text='Product or Service Provider.', null=True, verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reputation',
            field=models.FloatField(default=5.0, help_text='Buying or selling products or services.', null=True),
        ),
    ]
