# Generated by Django 3.1 on 2020-10-12 01:06

from django.db import migrations, models
import sunnysouth.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201006_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=sunnysouth.utils.models.generate_uuid, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=sunnysouth.utils.models.generate_uuid, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_supplier',
            field=models.BooleanField(default=False, help_text='Product or Service Provider.', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reputation',
            field=models.FloatField(default=5.0, help_text='Buying or selling products or services.'),
        ),
    ]
