# Generated by Django 3.1 on 2020-10-12 05:09

from django.db import migrations, models
import sunnysouth.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_generate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=sunnysouth.utils.models.generate_uuid, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=sunnysouth.utils.models.generate_uuid, max_length=300, unique=True),
        ),
    ]
