# Generated by Django 3.1 on 2020-10-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201012_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
