# Generated by Django 3.0.8 on 2020-07-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200530_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='canceled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
