# Generated by Django 3.1 on 2020-10-12 01:06

from django.db import migrations, models
import sunnysouth.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_canceled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=sunnysouth.utils.models.generate_uuid, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.CharField(default=sunnysouth.utils.models.generate_uuid, max_length=300),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='uuid',
            field=models.CharField(default=sunnysouth.utils.models.generate_uuid, max_length=300),
        ),
        migrations.AddField(
            model_name='sale',
            name='uuid',
            field=models.CharField(default=sunnysouth.utils.models.generate_uuid, max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='custom_features',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client_ranking',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='location',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='supplier_raking',
            field=models.FloatField(default=5.0),
        ),
    ]
