# Generated by Django 3.1 on 2020-10-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20201018_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'product_category', 'verbose_name_plural': 'product_categories'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='code',
        ),
    ]
