name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker stack
      run: docker-compose -f local.yml build --no-cache
    - name: Run Tests
      run: docker-compose -f local.yml run --rm django pytest
