name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build docker stack
      run: docker-compose -f local.yml build
    - name: Run Tests
      run: docker-compose -f local.yaml run --rm django python manage.py test sunnysouth/
